const disease_names = [
  "Apple scab",
  "Apple Black rot",
  "Apple Cedar apple rust",
  "Healthy Apple",
  "Blueberry Healthy",
  "Cherry Powdery mildew",
  "Cherry Healthy",
  "Corn(maize) Cercospora leaf spot(Gray leaf spot)",
  "Corn(maize) CommonRust",
  "Corn_(maize) Northern Leaf Blight",
  "Corn(maize) Healthy",
  "Grape Black rot",
  "Grape Esca(Black_Measles)",
  "Grape Leaf blight(Isariopsis_Leaf_Spot)",
  "Grape Healthy",
  "Orange Haunglongbing(Citrus_greening)",
  "Peach Bacterial Spot",
  "Peach Healthy",
  "Pepper Bell Bacterial Spot",
  "Pepper Bell Healthy",
  "Potato Early blight",
  "Potato Late blight",
  "Potato Healthy",
  "Raspberry Healthy",
  "Soybean Healthy",
  "Squash Powdery mildew",
  "Strawberry Leafscorch",
  "Strawberry Healthy",
  "Tomato Bacterial spot",
  "Tomato Early blight",
  "Tomato Late blight",
  "Tomato Leaf Mold",
  "Tomato Septoria leaf spot",
  "Tomato Spider mites",
  "Tomato Target Spot",
  "Tomato Yellow Leaf Curl Virus",
  "Tomato mosaic virus",
  "Tomato Healthy"
];
const disease_info = [
"Apple scab is a common disease of plants in the rose family (Rosaceae) that is caused by the ascomycete fungus Venturia inaequalis. While this disease affects several plant genera, including Sorbus, Cotoneaster, and Pyrus, it is most commonly associated with the infection of Malus trees, including species of flowering crabapple, as well as cultivated apple. The first symptoms of this disease are found in the foliage, blossoms, and developing fruits of affected trees, which develop dark, irregularly-shaped lesions upon infection." , "The fungus Botryosphaeria obtusa can cause devastating losses to apples and crabapples over a wide geographical range and especially in warm humid climates. Part of the reason why this fungus is so widespread and ready to attack your apple and crabapple trees is that it grows on the dead tissue of many other host plants. However, its ability to cause disease is limited mainly to pome fruits (apples and pears)." , "Cedar apple rust (Gymnosporangium juniperi-virginianae) is a fungal disease that requires juniper plants to complete its complicated two year life-cycle. Spores overwinter as a reddish-brown gall on young twigs of various juniper species. In early spring, during wet weather, these galls swell and bright orange masses of spores are blown by the wind where they infect susceptible apple and crab-apple trees. The spores that develop on these trees will only infect junipers the following year. From year to year, the disease must pass from junipers to apples to junipers again; it cannot spread between apple trees." , "Apple is healthy" , "Blue berry is healthy" , "Powdery mildew of sweet and sour cherry is caused by Podosphaera clandestina, an obligate biotrophic fungus. Mid- and late-season sweet cherry (Prunus avium) cultivars are commonly affected, rendering them unmarketable due to the covering of white fungal growth on the cherry surface" , "Cherry is healthy" , "Grey leaf spot (GLS) is a foliar fungal disease that affects maize, also known as corn. GLS is considered one of the most significant yield-limiting diseases of corn worldwide. There are two fungal pathogens that cause GLS: Cercospora zeae-maydis and Cercospora zeina. Gray leaf spot on corn, caused by the fungus Cercospora zeae-maydis, is a peren- nial and economically damaging disease in the United States." , "Common rust is caused by the fungus Puccinia sorghi and occurs every growing season. It is seldom a concern in hybrid corn. Rust pustules usually first appear in late June. Early symptoms of common rust are chlorotic flecks on the leaf surface. These soon develop into powdery, brick-red pustules as the spores break through the leaf surface. Pustules are oval or elongated, about 1/8 inch long, and scattered sparsely or clustered together. The leaf tissue around the pustules may become yellow or die, leaving lesions of dead tissue. The lesions sometimes form a band across the leaf and entire leaves will die if severely infected. As the pustules age, the red spores turn black, so the pustules appear black, and continue to erupt through the leaf surface. Husks, leaf sheaths, and stalks also may be infected." , "Setosphaeria turcica; the asexual stage name is Exserohilum turcicum. It has also been known as Helminthosporium turcicum. There are many races or strains of the fungus. Large, usually oval, grey or light brown leaf spots, sometimes with dark margins, 25-150 mm long (Photos 1&2). The spots merge covering large parts of the leaves. Symptoms occur first on the lower leaves, except when plants become infected by large numbers of spores from the atmosphere. In moist weather, brown fungal growth containing spores occurs on the spots, often in concentric zones. The disease causes the leaves to dry out, wither and die." , "Corn is healthy" , "Black rot is one of the most damaging diseases of grapes in Ohio and other northeastern states. The disease is caused by the fungus Guignardia bidwellii. The fungus can infect the leaves, shoots, berries, tendrils, rachises and cluster stems (peduncles) of grapes. If the disease is not managed early in the season, the impact on grape clusters can be devastating, resulting in complete crop losses." , "Esca is a grape disease of mature grapevines. It is a type of grapevine trunk disease. The fungi Phaeoacremonium aleophilum, Phaeomoniella chlamydospora[1] and Fomitiporia mediterranea[2] are associated with the disease." , "The yellow-green disease spots gradually appear on the fronts of the grape leaves with downy mildew, and white frosty mildew appears on the backs of the leaves. Leaf blight produces dark brown patches on the surface of grape leaves. The differences among these disease spots contribute to the recognition of various grape leaf diseases." , "Grape is healthy." , "Huanglongbing (HLB) or citrus greening is the most severe citrus disease, currently devastating the citrus industry worldwide. The presumed causal bacterial agent Candidatus Liberibacter spp. affects tree health as well as fruit development, ripening and quality of citrus fruits and juice. Fruit from infected orange trees can be either symptomatic or asymptomatic. Symptomatic oranges are small, asymmetrical and greener than healthy fruit. Furthermore, symptomatic oranges show higher titratable acidity and lower soluble solids, solids/acids ratio, total sugars, and malic acid levels. Among flavor volatiles, ethyl butanoate, valencene, decanal and other ethyl esters are lower, but many monoterpenes are higher in symptomatic fruit compared to healthy and asymptomatic fruit." , "Bacterial spot is an important disease of peaches, nectarines, apricots, and plums caused by Xanthomonas arboricola pv. pruni (XAP), formerly Xanthomonas campestris pv. pruni. The disease’s symptoms include fruit spots, leaf spots and twig cankers. Fruit symptoms include pitting, cracking, gumming and watersoaked tissue. Fruit infected by bacterial spot are more susceptible to other fruit diseases such as brown rot and rhizopus, as well as infestations by insects. Severe leaf spot infections can cause early defoliation. Severe defoliation can result in reduced fruit size, and sunburn and cracking of fruit. Early defoliated trees can be less vigorous and more prone to winter damage." , "Peach is healthy." , "Bacterial leaf spot, caused by Xanthomonas campestris pv. vesicatoria, is the most common and destructive disease for peppers in the eastern United States. It is a gram-negative, rod-shaped bacterium that can survive in seeds and plant debris from one season to another (Frank et al.) Different strains or races of the bacterium are cultivar-specific, causing disease symptoms in certain varieties due to stringent host specificity. Bacterial leaf spot can devastate a pepper crop by early defoliation of infected leaves and disfiguring fruit. In severe cases, plants may die as it is extremely difficult to find a cure once the disease takes hold. However, there are several options for growers to prevent it from occurring and spreading." , "Pepper bell is healthy." , "Early blight of potato is caused by the fungal pathogen Alternaria solani. The disease affects leaves, stems and tubers and can reduce yield, tuber size, storability of tubers, quality of fresh-market and processing tubers and marketability of the crop. In most production areas, early blight occurs annually to some degree. The severity of early blight is dependent upon the frequency of foliar wetness from rain, dew, or irrigation; the nutritional status of the foliage; and cultivar susceptibility.Across the Midwestern U.S., foliar infection is the most problematic phase of the disease, whereas in the western portion of the country, tuber infection can be more damaging." , "Late blight is caused by the funguslike oomycete pathogen Phytophthora infestans. This potentially devastating disease can infect potato foliage and tubers at any stage of crop development. The primary host is potato, but P. infestans also can infect other solanaceous plants, including tomatoes, petunias and hairy nightshade, that can act as source of inoculum to potato.In North America, late blight survives between seasons in infected seed tubers, cull piles and volunteer plants. Knowing the symptoms and disease cycle of this rapidly destructive disease is necessary to implement management options." , "Potato is healthy." , "Raspberry is healthy." , "Soybean is healthy." , "The first sign of powdery mildew on squash are small, white, dusty spots on the young leaves. Initially, there will only be a few spots, but it spreads quickly, eventually covering the entire leaf surface. Powdery mildew is most commonly seen on the top of the leaves, but it can also appear on the leaf undersides, the stems, and even on the fruits. Some varieties of squash naturally have white markings on the leaves. This makes it difficult to tell whether the presence of white spots is merely a physical trait of that variety or the start of a powdery mildew infection. The easiest way to tell is to look at the patterns of the white splotches." , "Scorched strawberry leaves are caused by a fungal infection which affects the foliage of strawberry plantings. The fungus responsible is called Diplocarpon earliana. Strawberries with leaf scorch may first show signs of issue with the development of small purplish blemishes that occur on the topside of leaves." , "Strawberry is healthy." , "Bacterial spot of tomato is caused by Xanthomonas vesicatoria, Xanthomonas euvesicatoria, Xanthomonas gardneri, and Xanthomonas perforans. These bacterial pathogens can be introduced into a garden on contaminated seed and transplants, which may or may not show symptoms." , "Early blight is one of the most common tomato and potato diseases, occurring nearly every season in Minnesota.It affects leaves, fruits and stems and can be severely yield-limiting when susceptible tomato cultivars are used and weather is favorable.Severe defoliation can occur.  In tomatoes, fruit can be damaged by sun." , "Tomato late blight is caused by the oomycete pathogen Phytophthora infestans (P. infestans). The pathogen is best known for causing the devastating Irish potato famine of the 1840s, which killed over a million people, and caused another million to leave the country. The first symptoms of late blight on tomato leaves are irregularly shaped, water-soaked lesions, often with a lighter halo or ring around them. These lesions are typically found on the younger, more succulent leaves in the top portion of the plant canopy." , "Tomato leaf mold is typically only an issue in greenhouse and high-tunnel tomatoes.The disease is driven by high relative humidity (greater than 85%).Foliage is often the only part of the plant directly infected. Infection will cause infected leaves to wither and die, indirectly affecting yield.In severe cases, blossoms and fruit can also be infected, directly reducing yield.Leaf mold is caused by the fungus Passalora fulva (previously called Fulvia fulva or Cladosporium fulvum)." , "Septoria leaf spot is caused by the fungus Septoria lycopersici. This fungus can attack tomatoes at any stage of development, but symptoms usually first appear on the older, lower leaves and stems when plants are setting fruit. Symptoms usually appear on leaves, but can occur on petioles, stems, and the calyx." , "The two-spotted spider mite is the most common mite species that attacks vegetable and fruit crops in New England. Spider mites can occur in tomato, eggplant, potato, vine crops such as melons, cucumbers, and other crops. Two-spotted spider mites are one of the most important pests of eggplant." , "Also known as early blight, target spot of tomato is a fungal disease that attacks a diverse assortment of plants, including papaya, peppers, snap beans, potatoes, cantaloupe, and squash as well as passion flower and certain ornamentals. Target spot on tomato fruit is difficult to control because the spores, which survive on plant refuse in the soil, are carried over from season to season." , "Tomato yellow leaf curl virus is a species in the genus Begomovirus and family Geminiviridae. Tomato yellow leaf curl virus (TYLCV) infection induces severe symptoms on tomato plants and causes serious yield losses worldwide. TYLCV is persistently transmitted by the sweetpotato whitefly, Bemisia tabaci (Gennadius)." , "Tomato mosaic virus (ToMV) is a plant pathogenic virus. It is found worldwide and affects tomatoes and many other plants. The foliage of affected tomato plants shows mottling, with alternating yellowish and darker green areas, the latter often appearing thicker and raised giving a blister-like appearance. The leaves tend to be fern-like in appearance with pointed tips and younger leaves may be twisted. The fruit may be distorted, yellow blotches and necrotic spots may occur on both ripe and green fruit and there may be internal browning of the fruit wall." , "Tomato is healthy." 
];
const rec_pest = [
["Anilinopyrimidine(AP)fungicides" , "Tebuconazole" , "Myclobutanil" , "Captan" , "Chlorothalonil."],
[" Neem oil" , "Jojoba oil" , "Horticultural oil"],
["Myclobutanil"],
["No Need"],
["No Need"],
["azoxystrobin" , "pyraclostrobin" , "penthiopyrad" , "flutianil"],
["No Need"],
["azoxystrobin" , "pyraclostrobin" , "fluoxastrobin"],
["Comet (Pyraclostrobin)" , "Quilt Xcel (Azoxystrobin + propiconazole)"],
["chlorothalonil", "mancozeb"],
["No Need"],
["Mancozeb" , "Ziram"],
["azoxystrobin" , "copper hydroxide" , "fenhexamid"],
["Phostrol Agricultural Fungicide" , "Pristine Fungicide (pyraclostrobin + boscalid)"],
["No Need"],
["oxytetracycline" , "streptomycin"],
["Permethrin."],
["No Need"],
["Aprovia Top" , "Quadris" , "Quadris Top" , "Cabrio"],
["No Need"],
["Bayer Garden Blight Control" , "imidacloprid"],
["mancozeb + chlorothalonil, 62.5 +12.5 percent"],
["No Need"],
["No Need"],
["No Need"],
["Bonide Sulfur Plant Fungicide" , "BONIDE Copper Fungicide Dust"],
["Abound 2.08F" , "Cabrio 20EG" , "Pristine 38WG"],
["No Need"],
["copper with mancozeb"],
["Bonide Liquid Copper Fungicide concentrate" , "Bonide Tomato & Vegetable"],
["Penncozeb" , "Manzate" , "Dithane"],
["copper hydroxide"],
["maneb" , "mancozeb" , "chlorothalonil" , "benomyl"],
["Diatomaceous Earth" , "Doktor Doom Spider Mite Knockout" , "Floramite SC"],
["chlorothalonil" , "Bonide Copper Fungicide RTU"],
["dinotefuran (Venom)" , "thiamethoxam (Platinum)"],
["Safer Soap" , "Bon-Neem" , "diatomaceous earth"],
["No Need"],

];

const disease_img = ["Apple_scab.jpg" , "Apple_Black_rot.jpg" , "Apple_Cedar_apple_rust.png" , "Apple_healthy.jpg" , "Blueberry_healthy.jpg" , "Cherry(including_sour)__Powdery_mildew.jpg" , "Cherry(including_sour)__healthy.jpg" , "Corn(maize)__Cercospora_leaf_spot Gray_leaf_spot.jpg" , "Corn(maize)__Common_rust.png" , "Corn_(maize)__Northern_Leaf_Blight.jpg" , "Corn(maize)__healthy.jpg" , "Grape_Black_rot.jpg" , "Grape_Esca(Black_Measles).jpg" , "Grape__Leaf_blight(Isariopsis_Leaf_Spot).jpg" , "Grape__healthy.jpg" , "Orange_Haunglongbing(Citrus_greening).jpg" , "Peach__Bacterial_spot.jpg" , "Peach_healthy.jpg" , "Pepper_bell_Bacterial_spot.jpg" , "Pepper_bell_healthy.jpg" , "Potato_Early_blight.jpg" , "Potato_Late_blight.jpg" , "Potato_healthy.jpg" , "Raspberry_healthy.jpg" , "Soybean_healthy.jpg" , "Squash_Powdery_mildew.jpg" , "Strawberry_Leaf_scorch.jpg" , "Strawberry_healthy.jpg" , "Tomato_Bacterial_spot.jpg" , "Tomato_Early_blight.jpg" , "Tomato_Late_blight.jpg" , "Tomato_Leaf_Mold.jpg" , "Tomato_Septoria_leaf_spot.jpg" , "Tomato_Spider_mites Two-spotted_spider_mite.jpg" , "Tomato_Target_Spot.jpg" , "Tomato_Tomato_Yellow_Leaf_Curl_Virus.jpg" , "Tomato_Tomato_mosaic_virus.jpg" , "Tomato_healthy.jpg"];
